### ISSUE TITLE
Tests are going to fails without being adjusted first

### ISSUE THREAD

**Issue by icefapper** [JazzleWare/jazzle-parser#5]
Hello
Just wantd to say jsRube's AST are slightly different from those of esprima;  for example, while jsRube keeps nodes' start and end locations ('loc') in 'start' and 'end', respectively, esprima keeps them in 'ranges'. The code at the beginning of the function 'compare' in module './util.js' is actually the 'adjuster' code. Thanks a lot reading this far.

**Comment by zenekron** [comment]
I thought something like that. The framework for testing is basically ready so we just need to hook the "adjuster" in.

**Comment by icefapper** [comment]
@zenekron 
Wow! That is goin to be awesome! I'm going to prepare the adjuster.
Could I ask you hook it in when I get it functioning? Thanks :)

**Comment by zenekron** [comment]
@icefapper 
I hope that I removed all the unnecessary break statements I added and I refactored a bit the test runner.  
If you open the `test/source.js` you can see that there's a method for running tests over a test tree, it's second argument is a function that returns an AST from the given source. That way it should be pretty straight-forward to hook in the adjuster!
