### ISSUE TITLE
What should the error reported by `function *l() { (yield=12)=>12; }`  be?

### ISSUE THREAD

**Issue by nenionoda** [JazzleWare/jazzle-parser#6]
Hello
as it currently stands, this results in a 'unexpected =`; i know it is being rather too pedantic, and that it might require extra work to achieve it, but I believe it should be 'invalid parameter name: yield' instead.

**Comment by icefapper** [comment]
`yield` is an actual **keyword** in generator context; as a result, `(yield=12)=>12` inside a generator is as much an error as `(while=12)=>12` is. ADHD is nothing to be ashamed about ([Zooey Deschanel](https://en.wikipedia.org/wiki/Ron_Jeremy) also has it.)

But please make sure you are no longer inflicted with the next time you file a ticket on this repo.
