### ISSUE TITLE
Typo at `src/statement@Parser.js#366`

### ISSUE THREAD

**Issue by zenekron** [JazzleWare/jazzle-parser#9]
While working on the 0.6 version I noticed what I think is a typo at [src/statement@Parser.js#366](https://github.com/JazzleWare/jazzle-parser/blob/master/src/statement%40Parser.js#L366):
```js
this.err('switch.has.no.opening.curly', startc, stratLoc));
```

I suppose that the third argument should be `startLoc` instead of `stratLoc`.

**Comment by icefapper** [comment]
@zenekron 
fixing.... :)

**Comment by zenekron** [comment]
@icefapper just found at [src/pattern@Parser.js#144](https://github.com/JazzleWare/jazzle-parser/blob/master/src/pattern%40Parser.js#L144) a `starc` which supposedly should be `startc`

**Comment by icefapper** [comment]
@zenekron I have completely removed what was going to be the main hub for error tracking and failure tolerance; that mostly includes the mess following the pattern below:
```js
if ( ... this.err(<error.name>, <error.params>) return this.errorHandlerOutput
```

We will have to bring it back at some point, when the things have become more streamlined and less error prone, but in the meantime, it should resolve this issue.

Thanks again for reminding me about it.

Have a great holiday, by the way :wink:
